# -*- coding: utf-8 -*-
"""Via Codos website — all approved copy from the content document."""

SERVICES = [
 dict(slug="it-outsourcing", name="IT Outsourcing & Staff Augmentation", icon="users",
  group="Talent & Intelligence", tagline="Talent, On Demand",
  meta_title="IT Outsourcing & Staff Augmentation | Via Codos",
  meta_desc="Extend your engineering capacity in days, not months, with dedicated Sri Lankan software professionals who work inside your workflow, your timezone overlap, and your standards.",
  oneliner="Extend your engineering capacity in days, not months, with dedicated Sri Lankan software professionals who work inside your workflow, your timezone overlap, and your standards.",
  body=["Hiring is slow, expensive, and increasingly uncertain in saturated Western talent markets. Via Codos removes that bottleneck by giving you direct access to a vetted bench of software engineers, QA specialists, DevOps practitioners, and product designers who can be onboarded into your team within one to three weeks.",
   "Every engineer we place has passed a four-stage evaluation: technical screening, live coding assessment, architecture and system-design interview, and a communication and culture-fit review. You are not outsourcing to a call-centre model — you are extending your own engineering organisation with professionals who attend your stand-ups, use your tools, and report to your leads.",
   "Engagements can be structured as full-time dedicated resources, fractional specialists for short bursts of work, or complete pods (a lead, two to four engineers, and a QA engineer) that operate as a self-contained delivery unit. Contracts scale up or down with 30 days' notice, so your headcount always matches your roadmap — not the other way around."],
  included=["Dedicated engineers who work exclusively on your codebase",
   "Flexible engagement models: individual hires, pods, or full teams",
   "4-8 hour overlap with US, UK, EU, and Australian business hours",
   "Monthly performance reviews and transparent time-tracking",
   "Replacement guarantee if a placed engineer is not the right fit",
   "No recruitment fees, visa sponsorship, or local payroll administration"],
  stat=("100+","Pre-vetted engineers ready to deploy")),
 dict(slug="custom-software", name="Custom Software Development", icon="code",
  group="Build", tagline="Built Around Your Problem, Not a Template",
  meta_title="Custom Software Development | Via Codos",
  meta_desc="End-to-end design, engineering, and delivery of bespoke applications that solve the specific operational problems off-the-shelf software cannot.",
  oneliner="End-to-end design, engineering, and delivery of bespoke applications that solve the specific operational problems off-the-shelf software cannot.",
  body=["Packaged software forces your business to bend around its limitations. Custom software does the opposite. Via Codos designs and builds applications — from internal operations tools to customer-facing platforms — engineered specifically around how your business actually runs.",
   "Our delivery model follows a disciplined, agile methodology: a discovery phase to map requirements and constraints, architecture and technical design sign-off before a single line of production code is written, two-week sprints with demo-able increments, and continuous QA rather than a single testing phase at the end. You always know what is being built, why, and when you will see it.",
   "We build on modern, maintainable stacks — Java/Spring, .NET, Node.js, Python/Django, React, Vue, and Flutter among others — and we document everything we ship, so your software is never a black box that only we understand."],
  included=["Requirement discovery and technical architecture workshops",
   "Agile delivery in two-week sprints with live demos",
   "Full ownership of source code, documentation, and IP",
   "Automated testing built in from sprint one, not bolted on later",
   "Post-launch warranty period and ongoing support options",
   "Legacy system modernisation and re-platforming"],
  stat=("100+","Custom solutions delivered")),
 dict(slug="erp-development", name="ERP Development", icon="layers",
  group="Run & Scale", tagline="One System of Record, Zero Guesswork",
  meta_title="ERP Development | Via Codos",
  meta_desc="Purpose-built enterprise resource planning systems that unify inventory, finance, HR, and operations for automotive, retail, manufacturing, and service businesses.",
  oneliner="Purpose-built enterprise resource planning systems that unify inventory, finance, HR, and operations for automotive, retail, manufacturing, and service businesses.",
  body=["Most mid-market businesses run on a patchwork of spreadsheets, disconnected point tools, and manual reconciliation. That patchwork works — until it doesn't, and the cost of that failure shows up as stockouts, payroll errors, or a finance team that closes the books three weeks late.",
   "Via Codos designs ERP systems that replace the patchwork with a single source of truth. We have deep, proven experience delivering vertical-specific ERP — our BeltKit platform for automotive service centres is a live example — as well as building bespoke ERP modules for clients whose operations do not fit a generic package.",
   "Because we build rather than license, your ERP evolves with your business instead of forcing your business to adapt to a vendor's release cycle. There are no per-seat licensing surprises and no waiting eighteen months for a vendor roadmap item you need today."],
  included=["Inventory and warehouse management with real-time stock visibility",
   "Supply chain and procurement workflows",
   "Financial modules: invoicing, accounts payable/receivable, reporting",
   "HR and payroll administration",
   "Role-based dashboards and configurable analytics",
   "Integration with existing accounting, POS, and CRM systems"],
  stat=("40+","ERP systems implemented")),
 dict(slug="web-development", name="Web Development", icon="globe",
  group="Build", tagline="Fast, Modern, Built to Convert",
  meta_title="Web Development | Via Codos",
  meta_desc="Responsive websites and web applications engineered for performance, search visibility, and measurable business outcomes.",
  oneliner="Responsive websites and web applications engineered for performance, search visibility, and measurable business outcomes.",
  body=["A website is frequently the first, and sometimes the only, interaction a prospect has with your business before deciding whether to trust you. Via Codos builds websites and web applications that are fast, accessible, secure, and structured around conversion — not just visually pleasing.",
   "Our front-end teams work in React, Vue, and Next.js; our back-end teams work in Node.js, Django, Laravel, and .NET, matched to the complexity and scale of what you're building. Every site we ship is built mobile-first, tested across browsers and devices, and optimised for Core Web Vitals so it performs well in both user experience and search ranking.",
   "Whether you need a marketing site, a customer portal, a SaaS product, or a complex e-commerce platform, we scope, design, build, and maintain it as a long-term digital asset rather than a one-off project."],
  included=["Custom front-end and back-end development",
   "CMS integration (WordPress, Strapi, Sanity, headless architectures)",
   "E-commerce platforms and payment gateway integration",
   "Search engine optimisation built into the technical foundation",
   "Performance optimisation and Core Web Vitals tuning",
   "Ongoing maintenance, security patching, and hosting support"],
  stat=("200+","Websites developed")),
 dict(slug="mobile-apps", name="Mobile App Development", icon="smartphone",
  group="Build", tagline="Native Feel. Cross-Platform Speed.",
  meta_title="Mobile App Development | Via Codos",
  meta_desc="iOS and Android applications engineered for smooth performance, App Store approval on the first submission, and long-term maintainability.",
  oneliner="iOS and Android applications engineered for smooth performance, App Store approval on the first submission, and long-term maintainability.",
  body=["Mobile is often where customer loyalty is won or lost — a slow, buggy, or confusing app gets deleted within days. Via Codos designs and builds mobile applications that feel native, perform reliably on real-world devices and networks, and are architected to be extended rather than rebuilt as your product grows.",
   "We work in native Swift and Kotlin for performance-critical applications, and React Native or Flutter when a shared codebase across iOS and Android meaningfully accelerates your timeline and budget without compromising user experience. Our teams manage the entire lifecycle, including App Store and Google Play submission, so launch day doesn't get derailed by a rejected build.",
   "Post-launch, we provide monitoring, crash reporting, and iterative feature releases, treating your app as a living product rather than a delivered artefact."],
  included=["Native iOS (Swift) and Android (Kotlin) development",
   "Cross-platform development with React Native and Flutter",
   "App Store and Google Play submission and compliance management",
   "Push notifications, offline mode, and in-app analytics",
   "Third-party API and payment gateway integration",
   "Post-launch monitoring, crash reporting, and version updates"],
  stat=("50+","Mobile apps launched")),
 dict(slug="ui-ux-design", name="UI/UX Design", icon="pen",
  group="Build", tagline="Design That Earns Trust in Seconds",
  meta_title="UI/UX Design | Via Codos",
  meta_desc="User research, wireframing, and interface design that turns visitors into customers and complex workflows into simple ones.",
  oneliner="User research, wireframing, and interface design that turns visitors into customers and complex workflows into simple ones.",
  body=["Good design is not decoration — it is the difference between a customer completing a purchase and abandoning a cart, or between an employee adopting new software and quietly reverting to a spreadsheet. Via Codos treats UI/UX as a discipline grounded in research and measurable outcomes, not personal taste.",
   "Our process begins with user research and stakeholder interviews to understand real workflows and friction points, followed by low-fidelity wireframing to validate structure before any visual design begins. High-fidelity prototypes are then tested with real users so that costly design mistakes are caught before development, not after.",
   "The result is an interface system — components, patterns, and a design language — that your engineering team can build from consistently, and that your users find intuitive without needing an onboarding tutorial."],
  included=["User research, interviews, and persona development",
   "Information architecture and user-flow mapping",
   "Wireframing and interactive prototyping",
   "Visual design systems and component libraries",
   "Usability testing with real target users",
   "Accessibility (WCAG) compliance review"],
  stat=("95%","Client satisfaction rate")),
 dict(slug="ai-automation", name="AI & Automation", icon="cpu",
  group="Talent & Intelligence", tagline="Intelligence That Works While You Sleep",
  meta_title="AI & Automation | Via Codos",
  meta_desc="Conversational AI, workflow automation, and predictive analytics that reduce operating costs and eliminate repetitive manual work.",
  oneliner="Conversational AI, workflow automation, and predictive analytics that reduce operating costs and eliminate repetitive manual work.",
  body=["Every business has processes that are repetitive, rules-based, and expensive to staff around the clock — customer inquiries, appointment scheduling, data entry, lead qualification. Via Codos builds AI and automation systems that take on exactly that class of work, reliably and at a fraction of the cost of human staffing for the same volume.",
   "Our flagship capability, the AI Call Colleague, is a natural-language voice agent that answers calls, books appointments, and captures leads twenty-four hours a day, handling unlimited concurrent calls without hold times. Beyond voice, we build chat-based support agents, document-processing pipelines, and predictive models that flag risk or opportunity before a human would notice it.",
   "We are deliberately conservative about where full automation is appropriate. Every AI system we deploy includes clear escalation paths to a human, transparent logging, and guardrails against the kind of unsupervised errors that damage customer trust."],
  included=["24/7 conversational AI for calls and chat",
   "Natural language processing and intent recognition",
   "Workflow and business-process automation",
   "Predictive analytics and anomaly detection",
   "Human-in-the-loop escalation and oversight",
   "Integration with existing CRM, helpdesk, and scheduling tools"],
  stat=("24/7","Automated support availability")),
 dict(slug="cloud-devops", name="Cloud Solutions & DevOps", icon="cloud",
  group="Run & Scale", tagline="Infrastructure That Scales Without Drama",
  meta_title="Cloud Solutions & DevOps | Via Codos",
  meta_desc="Cloud migration, infrastructure automation, and DevOps pipelines that keep systems reliable as you grow.",
  oneliner="Cloud migration, infrastructure automation, and DevOps pipelines that keep systems reliable as you grow.",
  body=["Uptime and scalability are not features you add later — they are architectural decisions you make early, and Via Codos brings that discipline to every infrastructure engagement. We help businesses migrate from on-premise systems to AWS, Azure, or Google Cloud, right-size existing cloud spend, and build the automated deployment pipelines that let your engineering team ship changes safely and often.",
   "Our DevOps practice covers containerisation with Docker and Kubernetes, infrastructure-as-code with Terraform, and continuous integration/continuous deployment pipelines that catch problems before they reach production. We also implement monitoring and alerting so that when something does go wrong, your team knows about it before your customers do.",
   "Security and cost control are built into the architecture from the outset, not audited in after the fact — meaning fewer surprise bills and fewer 2 a.m. incident calls."],
  included=["Cloud migration and multi-cloud architecture (AWS, Azure, GCP)",
   "Infrastructure-as-code and automated provisioning",
   "CI/CD pipeline design and implementation",
   "Container orchestration with Docker and Kubernetes",
   "Monitoring, logging, and incident alerting",
   "Cost optimisation and cloud spend audits"],
  stat=("99.9%","Uptime guaranteed")),
 dict(slug="cybersecurity", name="Cybersecurity & Compliance", icon="shield",
  group="Talent & Intelligence", tagline="Protecting What Your Business Cannot Afford to Lose",
  meta_title="Cybersecurity & Compliance | Via Codos",
  meta_desc="Security assessments, hardened engineering practices, and compliance support that protect your data, your customers, and your reputation.",
  oneliner="Security assessments, hardened engineering practices, and compliance support that protect your data, your customers, and your reputation.",
  body=["Every engagement at Via Codos operates under an NDA-first discipline, but security cannot stop at paperwork. Our engineering teams build with secure coding standards from the first commit, and we offer dedicated security services for organisations that need a deeper level of assurance — particularly those handling customer financial data, health information, or other regulated data classes.",
   "We conduct vulnerability assessments and penetration testing against web and mobile applications, review cloud infrastructure for misconfiguration, and help clients prepare for compliance frameworks such as SOC 2, GDPR, and PCI-DSS. Where a client's own compliance team needs technical evidence for an audit, we produce it.",
   "Security is treated as a continuous discipline rather than a one-time certificate: we recommend and can implement recurring assessment cycles so that new features don't quietly reintroduce old risks."],
  included=["Web and mobile application penetration testing",
   "Cloud infrastructure security review",
   "Secure coding standards embedded into development workflow",
   "GDPR, SOC 2, and PCI-DSS compliance readiness support",
   "Data encryption, access control, and audit logging implementation",
   "Incident response planning"],
  stat=("100%","NDA compliance across every engagement")),
 dict(slug="qa-testing", name="QA & Test Automation", icon="flask",
  group="Run & Scale", tagline="Catch It Before Your Customers Do",
  meta_title="QA & Test Automation | Via Codos",
  meta_desc="Manual and automated testing practices that reduce production defects and shorten release cycles.",
  oneliner="Manual and automated testing practices that reduce production defects and shorten release cycles.",
  body=["The cost of a bug found in production is many times the cost of the same bug found in a code review. Via Codos builds QA into the development process itself rather than treating it as a final gate before release, combining structured manual testing with automated regression suites that run on every code change.",
   "Our QA engineers write test plans directly from requirements and user stories, so coverage maps to real usage rather than guesswork. Automated suites — built with tools such as Selenium, Cypress, and JUnit — run in your CI/CD pipeline, giving your team an immediate signal when a change breaks existing functionality.",
   "For clients with existing applications and no formal QA process, we can run an initial audit, establish a test strategy, and stand up automation incrementally without disrupting your current release schedule."],
  included=["Manual functional, regression, and exploratory testing",
   "Automated test suite development (Selenium, Cypress, JUnit, TestRail)",
   "Performance and load testing",
   "API and integration testing",
   "Continuous testing embedded in CI/CD pipelines",
   "Test strategy audits for existing applications"],
  stat=("40%","Average reduction in post-release defects")),
 dict(slug="data-analytics", name="Data Engineering & Analytics", icon="chart",
  group="Run & Scale", tagline="Turning Raw Data Into Decisions",
  meta_title="Data Engineering & Analytics | Via Codos",
  meta_desc="Data pipelines, warehousing, and dashboards that give leadership a clear, current view of the business.",
  oneliner="Data pipelines, warehousing, and dashboards that give leadership a clear, current view of the business.",
  body=["Most businesses generate far more data than they actually use — it sits scattered across systems, unreconciled and too slow to query when a decision actually needs it. Via Codos builds the data infrastructure that closes that gap: pipelines that reliably move data from source systems into a clean, queryable warehouse, and dashboards that put the answers in front of the people who need them.",
   "We work with modern data stacks — including PostgreSQL, Snowflake, BigQuery, and dbt for transformation — and build visualisation layers in tools such as Power BI, Looker, or custom-built dashboards when off-the-shelf BI tools don't fit the workflow. Where appropriate, we layer predictive models on top of clean data to move reporting from 'what happened' to 'what's likely to happen next.'",
   "We size this work to the client: a small business may need a single reliable weekly report; an enterprise may need a full real-time analytics platform. Either way, the underlying engineering discipline is the same."],
  included=["ETL/ELT pipeline design and implementation",
   "Data warehousing and modelling",
   "Business intelligence dashboards and reporting",
   "Predictive and prescriptive analytics",
   "Data quality auditing and governance",
   "Integration across CRM, ERP, and third-party data sources"],
  stat=("10+","Industries served with custom analytics")),
]

INDUSTRIES = [
 dict(slug="real-estate", name="Real Estate", icon="building",
  meta_title="Real Estate Software & IT Solutions | Via Codos",
  intro="Real estate businesses run on volume and trust simultaneously — dozens of live listings, ongoing transactions, and clients who expect an immediate response. Via Codos builds the property management platforms, CRM systems, and listing portals that let agencies manage that volume without dropping the personal responsiveness that wins deals.",
  challenges=["Disconnected listing data across multiple portals",
   "Manual, error-prone transaction and document tracking",
   "Slow lead response times losing deals to competitors"],
  solutions=["Property Management Platforms","CRM & Lead Management Systems",
   "Listing & Syndication Portals","Digital Transaction & Document Processing"]),
 dict(slug="automotive", name="Automotive", icon="car",
  meta_title="Automotive Software & IT Solutions | Via Codos",
  intro="From single-location service centres to multi-branch dealer groups, automotive businesses need inventory, scheduling, and customer history to live in one place. Our BeltKit ERP platform was purpose-built for this industry and is now the backbone of over one hundred service centres, and we extend and customise it for businesses whose workflow needs go beyond the standard build.",
  challenges=["Fragmented parts inventory and reorder visibility",
   "Manual service scheduling and technician assignment",
   "No unified customer service history across visits"],
  solutions=["BeltKit ERP for Service Centres","Inventory & Parts Management",
   "Service Scheduling & Technician Dispatch","Customer Communication & Loyalty Tools"]),
 dict(slug="healthcare", name="Healthcare", icon="heart",
  meta_title="Healthcare Software & IT Solutions | Via Codos",
  intro="Healthcare technology carries a different weight than most software — errors and delays have direct consequences for patients. Via Codos builds patient management, scheduling, and telemedicine systems engineered with data privacy and clinical workflow accuracy as first-order requirements, not afterthoughts.",
  challenges=["Appointment no-shows and scheduling inefficiency",
   "Fragmented patient records across departments",
   "Limited remote-care capability"],
  solutions=["Patient Management Systems","Appointment Scheduling & Reminders",
   "Telemedicine Platforms","Healthcare Analytics & Reporting"]),
 dict(slug="retail-ecommerce", name="Retail & E-commerce", icon="cart",
  meta_title="Retail & E-commerce Software & IT Solutions | Via Codos",
  intro="Retail margins are won or lost in the details: stock accuracy, checkout speed, and whether a customer comes back. We build point-of-sale systems, inventory platforms, e-commerce storefronts, and loyalty programmes that give retailers the same operational sophistication as much larger competitors, without the enterprise price tag.",
  challenges=["Inventory mismatches between physical and online stores",
   "Cart abandonment and slow checkout experiences",
   "Weak customer retention and repeat-purchase tracking"],
  solutions=["Point-of-Sale (POS) Systems","Unified Inventory Management",
   "E-commerce Platform Development","Loyalty & Rewards Programmes"]),
 dict(slug="manufacturing", name="Manufacturing", icon="factory",
  meta_title="Manufacturing Software & IT Solutions | Via Codos",
  intro="Manufacturers compete on efficiency, quality consistency, and supply chain resilience. Via Codos delivers production planning tools, supply chain visibility platforms, and quality-control systems that reduce waste and give plant managers real-time insight instead of end-of-shift paperwork.",
  challenges=["Limited real-time visibility into production line status",
   "Supply chain disruptions caught too late",
   "Manual, paper-based quality control records"],
  solutions=["Production Planning & Scheduling","Supply Chain Visibility Platforms",
   "Quality Control & Compliance Systems","Manufacturing Analytics Dashboards"]),
 dict(slug="logistics", name="Logistics & Supply Chain", icon="truck",
  meta_title="Logistics & Supply Chain Software & IT Solutions | Via Codos",
  intro="Every inefficiency in a logistics network compounds — a poorly routed truck or an untracked shipment cascades into cost and customer dissatisfaction downstream. We build fleet management, tracking, and route optimisation systems that give logistics operators the visibility to fix problems before customers notice them.",
  challenges=["Inefficient, manually-planned delivery routes",
   "Poor real-time shipment visibility for customers",
   "Warehouse inventory discrepancies"],
  solutions=["Fleet Management Systems","Real-Time Shipment Tracking",
   "Route Optimisation Engines","Warehouse Management Systems"]),
 dict(slug="education", name="Education", icon="grad",
  meta_title="Education Software & IT Solutions | Via Codos",
  intro="Educational institutions are managing a bigger technology footprint than ever — learning management, student records, online delivery, and assessment — often with a fraction of a corporate IT budget. Via Codos builds education technology that is affordable to build and cheap to maintain, without compromising on reliability during exam season or enrolment peaks.",
  challenges=["Fragmented student information across departments",
   "Limited or unreliable online learning infrastructure",
   "Manual, time-consuming assessment and grading workflows"],
  solutions=["Learning Management Systems (LMS)","Student Information Systems",
   "Online Learning & Virtual Classroom Platforms","Digital Assessment Tools"]),
 dict(slug="travel-tourism", name="Travel & Tourism", icon="plane",
  meta_title="Travel & Tourism Software & IT Solutions | Via Codos",
  intro="Travel businesses live and die by the booking experience — a slow or confusing flow loses the sale to a competitor tab away. We build booking platforms, itinerary and tour management tools, and customer engagement systems that keep the experience smooth from the first search to the post-trip review.",
  challenges=["Booking abandonment due to slow or complex flows",
   "Manual coordination of tours, guides, and itineraries",
   "Weak post-trip engagement and repeat bookings"],
  solutions=["Booking & Reservation Platforms","Tour & Itinerary Management Systems",
   "Travel CRM & Guest Engagement","Multi-Currency & Multi-Language Support"]),
 dict(slug="financial-services", name="Financial Services & FinTech", icon="bank",
  meta_title="Financial Services & FinTech Software & IT Solutions | Via Codos",
  intro="Financial technology demands a level of engineering discipline that few outsourcing providers can meet — security, auditability, and regulatory awareness are non-negotiable. Via Codos builds lending platforms, payment integrations, and financial dashboards with a security-first engineering approach and full support for compliance evidence gathering.",
  challenges=["Regulatory compliance and audit-readiness pressure",
   "Legacy core systems that resist integration",
   "High expectations for uptime and transaction security"],
  solutions=["Digital Lending & Onboarding Platforms","Payment Gateway & Ledger Integration",
   "Financial Reporting Dashboards","Fraud Detection & Risk Analytics"]),
 dict(slug="hospitality", name="Hospitality", icon="bell",
  meta_title="Hospitality Software & IT Solutions | Via Codos",
  intro="Hospitality technology has to disappear into the background — guests should feel taken care of, not aware of the systems making it happen. We build property management systems, booking engines, and guest engagement platforms that keep front-of-house teams fast and back-of-house operations organised.",
  challenges=["Manual reservation and room-inventory management",
   "Disconnected guest data across booking channels",
   "Inconsistent guest communication and feedback loops"],
  solutions=["Property Management Systems (PMS)","Direct Booking Engines",
   "Guest Relationship & Feedback Platforms","Channel Manager Integrations"]),
 dict(slug="smb", name="Mid & Small Business", icon="briefcase",
  meta_title="IT Solutions for Small & Mid-Sized Businesses | Via Codos",
  intro="Small and mid-sized businesses face nearly the same technology risks as large enterprises — data loss, downtime, security breaches, systems that don't scale — but almost never have the budget or headcount for a dedicated in-house IT and engineering team. We act as the outsourced technology department these businesses can't yet justify building in-house, at a fraction of the cost of hiring full-time engineers.",
  challenges=["Reactive-only IT support with no monitoring until something fails",
   "Limited budget for a full-time in-house engineering team",
   "Security gaps that make smaller businesses easy targets",
   "Systems and software that don't scale as the business grows"],
  solutions=["Managed IT Support & Helpdesk","Right-Sized Custom Software Development",
   "Cybersecurity Essentials & Hardening","Cloud Migration & Cost Management"]),
 dict(slug="it-sector", name="External IT Sector", icon="network",
  meta_title="White-Label IT & Engineering Support for IT Companies | Via Codos",
  intro="IT companies, managed service providers, and software agencies face a particular version of the talent problem: they sell engineering capacity for a living, but their own hiring can't always keep pace with client demand. Turning down work — or delivering it late — costs reputation as well as revenue. We act as the white-label engineering bench these companies scale up and down as their own client pipeline requires.",
  challenges=["Client demand outpacing in-house engineering capacity",
   "Difficulty scaling headcount quickly for large or short-term projects",
   "Risk of delivery delays damaging client relationships",
   "Need for specialist skills (AI, DevOps, mobile) not held in-house"],
  solutions=["White-Label Development & Staff Augmentation",
   "Overflow & Surge Capacity for Peak Delivery Periods",
   "Specialist Skill Augmentation (AI, DevOps, QA, Mobile)",
   "NDA-First, Confidential Delivery Under Your Brand"]),
]

CASE_STUDIES = [
 dict(slug="beltkit", name="BeltKit ERP", sector="Automotive", image="beltkit-poster.jpg", video="beltkit.mp4", poster="beltkit-poster.jpg",
  meta_title="BeltKit ERP Case Study | Via Codos",
  meta_desc="How Via Codos built BeltKit, a purpose-built ERP now running in 100+ automotive service centres — 70% faster service delivery and 40% lower inventory costs.",
  headline="70% faster service delivery from booking to completion",
  client="A growing network of independent car service and repair centres struggling to scale beyond a single location without losing operational control.",
  challenge="Automotive service businesses typically run on a mix of spreadsheets, paper job cards, and disconnected point-of-sale tools. As our client expanded from one location to several, this patchwork broke down: technicians lacked visibility into parts availability, customer service history was inconsistent between branches, and management had no real-time view of revenue or inventory across the network.",
  solution="Via Codos designed and built BeltKit, a complete ERP platform purpose-built for automotive service and repair centres. BeltKit unifies job scheduling, parts inventory, technician assignment, customer history, and billing into a single system accessible from any branch, with role-based dashboards so owners see the whole network while technicians see only what's relevant to their queue.",
  implementation=["Discovery workshops across three branch locations to map real technician and front-desk workflows",
   "Modular build: inventory, scheduling, and billing modules delivered and validated independently before integration",
   "Migration of two years of historical service records with zero data loss",
   "On-site training for front-desk and technician staff prior to go-live"],
  results=[("70%","Faster service delivery from booking to completion"),
   ("40%","Reduction in inventory carrying costs"),
   ("100+","Service centres now running BeltKit"),
   ("Live","Real-time multi-branch revenue visibility")],
  quote="BeltKit changed how we run the business day to day — we finally have one number for inventory and one number for revenue, and both are always current."),
 dict(slug="qalam-mms", name="Qalam MMS", sector="Religious & Community Institutions", image="qalam-poster.jpg", video="qalam.mp4", poster="qalam-poster.jpg",
  meta_title="Qalam MMS Case Study | Via Codos",
  meta_desc="How Qalam MMS digitised prayer scheduling, donations, and community communication for 200+ institutions — with a 60% lift in community engagement.",
  headline="200+ institutions now running on the platform",
  client="A network of mosques and community religious institutions managing prayer scheduling, donations, and community communication largely by hand.",
  challenge="Religious institutions carry significant administrative weight with limited administrative staff: prayer time coordination, event scheduling, donation collection and receipting, and communication with a large and often dispersed community. Manual processes meant donations went untracked, events were poorly attended due to weak communication, and administrators spent hours on tasks that should have taken minutes.",
  solution="Via Codos built Qalam MMS (Mosque Management System), a purpose-built digital platform covering prayer time management, event scheduling, donation tracking with automated receipting, and community-wide communication tools including SMS and app notifications.",
  implementation=["Requirements gathered directly from institution administrators across multiple sites to reflect real operational needs, not assumptions",
   "Donation module built with full audit trail and automated receipt generation for transparency and accountability",
   "Multi-language support for community communication",
   "Phased rollout starting with a pilot institution before wider deployment"],
  results=[("200+","Institutions now running on the platform"),
   ("60%","Increase in community engagement with events and announcements"),
   ("100%","Transparent, auditable donation tracking across all sites"),
   ("Hours","Of administrative time saved every week")],
  quote="Qalam MMS gave our administrators their time back and gave our donors confidence that their contributions are tracked properly."),
 dict(slug="ai-call-colleague", name="AI Call Colleague", sector="AI & Automation", image="ai-call-colleague-poster.jpg", video="ai-call-colleague.mp4", poster="ai-call-colleague-poster.jpg",
  meta_title="AI Call Colleague Case Study | Via Codos",
  meta_desc="How AI Call Colleague delivers 24/7 call answering, appointment booking, and lead capture — with an 80% reduction in customer service staffing cost.",
  headline="24/7 call availability with zero missed after-hours leads",
  client="Small and mid-sized service businesses across multiple industries losing after-hours leads and struggling with high call volumes during peak hours.",
  challenge="Every missed call is a potential lost customer, but staffing a phone line around the clock is rarely affordable for a small or mid-sized business. Our clients were losing after-hours appointment requests and support inquiries to competitors who happened to answer first, while peak-hour call volume regularly overwhelmed existing staff.",
  solution="Via Codos built AI Call Colleague, a natural-language voice agent that answers calls twenty-four hours a day, handles appointment booking and lead capture, and escalates to a human team member whenever a call requires judgement the AI shouldn't exercise alone. The system integrates directly with each client's existing scheduling and CRM tools so no call information is lost or duplicated.",
  implementation=["Conversation design workshops to script realistic call flows per client, per industry",
   "Integration with existing scheduling, CRM, and helpdesk systems for each deployment",
   "Built-in escalation logic and human hand-off for complex or sensitive calls",
   "Continuous monitoring and conversation-quality review post-launch"],
  results=[("24/7","Call availability with zero missed after-hours leads"),
   ("80%","Reduction in customer service staffing cost"),
   ("50+","Businesses deployed across multiple industries"),
   ("100%","Consistent lead-capture quality regardless of call volume")],
  quote="We stopped losing after-hours bookings the week this went live. It pays for itself many times over."),
 dict(slug="realtor-grow", name="Realtor Grow ERP", sector="Real Estate",
  image="realtor-grow-poster.jpg", video="realtor-grow.mp4", poster="realtor-grow-poster.jpg",
  meta_title="Realtor Grow ERP Case Study | Via Codos",
  meta_desc="How Realtor Grow unified listings, lead routing, transactions, and commission tracking into one real-estate ERP \u2014 with 60% faster lead response.",
  headline="One pipeline from listing to closing \u2014 across every branch",
  client="A multi-branch real estate agency running listings, leads, and commissions across disconnected portals and spreadsheets.",
  challenge="Real estate agencies run on speed and trust, but the client's growth had outpaced its tools: listings lived on three different portals, leads arrived in personal inboxes, transaction paperwork moved by email, and commission calculations took days at the end of every month. Agents spent more time reconciling systems than showing properties, and management had no single view of the pipeline.",
  solution="Via Codos built Realtor Grow, a real-estate ERP that brings listings, lead routing, transaction milestones, document handling, and commission tracking into one system. Leads are automatically routed to the right agent with response-time tracking, every transaction moves through defined milestones with document checklists, and commissions calculate themselves from the closed deal record.",
  implementation=["Discovery sessions with agents, front desk, and finance to map the full listing-to-closing workflow",
   "Lead capture integrated with property portals and the agency website, with automated routing and follow-up reminders",
   "Transaction milestone engine with document checklists and digital signing integration",
   "Commission and revenue dashboards rolled out branch by branch"],
  results=[("60%","Faster average lead response time"),
   ("40%","Less admin time per transaction"),
   ("100%","Pipeline visibility from listing to closing"),
   ("Zero","Month-end commission reconciliation battles")],
  quote="For the first time we can see every deal, every stage, every branch on one screen \u2014 and commission day stopped being a fight."),
]

INSIGHTS = [
 dict(slug="it-outsourcing-2026", title="IT Outsourcing in 2026: The Data Behind a Strategic Shift",
  cat="Outsourcing", date="July 2026", read="6 min read",
  excerpt="The global IT outsourcing market has crossed a major threshold in 2026 — and what's driving it is no longer cost. It's talent.",
  body=["The global IT outsourcing market has crossed a major threshold in 2026, with most estimates now placing it at around $638 billion globally, growing toward $752 billion by 2031. What's more revealing than the size of that number is what's driving it. As recently as 2020, roughly 70% of organizations named cost reduction as their primary reason for outsourcing IT. In 2026, that figure has fallen to just 34%, replaced by something more strategic: access to specialized talent and speed to market.",
   "That shift is being forced by a genuine shortage of skilled people. The world is currently short an estimated 4.8 million cybersecurity specialists alone, and demand for AI, cloud, and modern software engineering talent continues to outpace what local hiring markets can supply. The result: around 90% of large enterprises now rely on outsourcing for at least one core IT function, and it's no longer just the biggest players — roughly 37% of small businesses now outsource at least part of their IT or business operations as well.",
   "What's also changed is what companies expect from an outsourcing relationship once they're in it. 81% of organizations say they want their outsourcing partner to act as a genuine strategic partner, not just an executor of tasks handed down to them. Nearly half of all outsourcing contracts today build in AI and automation components from the outset, and 87% of IT leaders say they rely on outsourcing specifically to accelerate their AI adoption and get faster returns on technology investment.",
   "The practical takeaway for any business weighing outsourcing today isn't \"should we save money by outsourcing\" — that's increasingly the wrong question. It's \"where is the specialized talent we need, and how fast can we responsibly bring it into our team.\" That's the version of outsourcing Via Codos builds every engagement around: not headcount arbitrage, but real engineering capacity, delivered fast, on your terms."]),
 dict(slug="global-talent-shortage", title="The Global Engineering Talent Shortage: Why Companies Are Looking Beyond Their Borders",
  cat="Outsourcing", date="July 2026", read="5 min read",
  excerpt="The conversation around global hiring has shifted from \"how do we cut costs\" to \"where do we actually find the people.\"",
  body=["The conversation around global hiring has quietly shifted from \"how do we cut costs\" to \"where do we actually find the people.\" The world is short an estimated 4.8 million cybersecurity specialists alone, and demand for engineers with modern cloud, AI, and full-stack skills continues to outpace what domestic hiring markets in the US, UK, and Australia can supply — a gap that shows up as longer hiring timelines and rising wages rather than empty job postings.",
   "That pressure is exactly why the composition of outsourcing demand has changed. Cybersecurity has gone from being one of the least outsourced IT functions in 2023 to the single most outsourced function in 2026, tied with general IT infrastructure at 72%. It's no longer just large enterprises making this move either — around 90% of large organizations now outsource at least one core IT function, and a growing share of small businesses are following the same path for the same reason: the talent they need simply isn't available fast enough locally.",
   "What's changed most is what businesses expect once they commit to this model. Roughly 81% of organizations now want an outsourcing partner to function as a genuine extension of their strategy, not a vendor executing a fixed spec, and nearly half of all new outsourcing contracts now build AI and automation capability in from day one rather than treating it as a future add-on.",
   "For a business weighing whether to keep trying to hire locally or open the door to international engineering talent, the honest framing in 2026 isn't a cost comparison anymore — it's a timeline comparison. The businesses moving fastest are the ones who've accepted that the best available engineer for a given problem might not be down the street, and have built a hiring process, like ours, that can bring that person onto the team in weeks rather than months."]),
 dict(slug="smb-cybersecurity-numbers", title="Small Business Cybersecurity by the Numbers: The Cost of Doing Nothing",
  cat="Cybersecurity", date="July 2026", read="6 min read",
  excerpt="Small businesses have quietly become the primary target of modern cybercrime — not despite their size but because of it.",
  body=["Small businesses have quietly become the primary target of modern cybercrime, not despite their size but because of it. Small and mid-sized businesses now experience roughly four times more confirmed data breaches than large organizations, and an estimated 43% of all cyberattacks are aimed specifically at small businesses — a figure several more recent industry reports suggest may now be even higher.",
   "The financial exposure is not abstract. The average total cost of a cyberattack on a small or mid-sized business is around $254,000, with some incidents running as high as $7 million. Ransomware is a particularly large share of that risk: roughly 80% of ransomware attacks target organizations with fewer than 1,000 employees, and among breached small businesses specifically, ransomware appears in about 88% of incidents, compared to only 39% of breaches at large enterprises.",
   "What makes this gap so persistent is a mismatch between risk and preparation. Nearly half of businesses with fewer than 50 employees allocate zero budget to cybersecurity at all, even though prevention typically costs 50 to 60 times less than recovery — a few thousand dollars a year in safeguards, against several hundred thousand dollars for a single incident. One of the simplest, highest-impact fixes remains one of the most neglected: multi-factor authentication blocks over 99.9% of automated account attacks, yet fewer than 34% of small businesses have implemented it.",
   "There's also a dangerous myth worth retiring directly. Roughly 44% of small businesses believe that having already been attacked once makes them less likely to be targeted again — the opposite of how attackers actually operate. A business that's been breached has demonstrated it can be breached, and without real changes to its security posture, it remains an easy repeat target.",
   "None of this requires an enterprise security budget to address meaningfully. It requires treating a handful of specific, well-understood gaps — MFA, monitored backups, basic access control — as non-negotiable rather than optional. That's exactly the standard our Cybersecurity & Compliance service is built around for clients who don't have an internal security team of their own."]),
 dict(slug="ai-automation-roi-2026", title="AI Automation ROI in 2026: What the Data Actually Shows",
  cat="AI & Automation", date="July 2026", read="6 min read",
  excerpt="AI automation has moved past the experimental phase — but the honest picture has two halves, and both matter.",
  body=["AI automation has clearly moved past the experimental phase. About 88% of enterprises now use AI in at least one business function, and customer service leads all departments in adoption at 56% — the same area where our own AI Call Colleague platform operates. The economics behind that lead are stark: AI can handle a customer interaction for roughly $0.50 to $0.70, compared to $6 to $8 for the same interaction handled by a human agent.",
   "For deployments that go well, the returns are substantial. Companies seeing measurable returns from AI automation report an average 5.8x ROI within 14 months, and AI-assisted teams in IT operations report roughly 31% fewer critical incidents and 28% faster resolution times. In manufacturing specifically, predictive-maintenance AI has been shown to cut equipment downtime by around 45% and maintenance costs by about 25%.",
   "But the honest picture has a second half that's just as important. Despite near-universal adoption, only around 6% of organizations report capturing significant value from their AI investment, and some estimates put the failure rate for AI projects as high as 80-95%. That gap is almost never about the underlying model. Most failures trace back to poor data quality and weak integration into real workflows, not the AI itself — and externally sourced AI builds reach successful deployment roughly twice as often as internal-only efforts, which is a meaningful data point for any business deciding whether to build this in-house or bring in a partner who has done it before.",
   "The takeaway isn't \"AI works\" or \"AI doesn't work\" — it's that AI automation succeeds or fails on the same fundamentals as any other software project: clean data, a well-scoped use case, and a partner who designs for the messy edge cases, not just the demo. That's precisely the discipline we bring to every AI & Automation engagement."]),
 dict(slug="software-budget-overruns", title="Why Most Software Projects Run Over Budget — And How to Not Be One of Them",
  cat="Technology", date="July 2026", read="6 min read",
  excerpt="Custom software has a reputation problem, and the data backs it up. But the causes are avoidable — if your process is built for them.",
  body=["Custom software has a reputation problem, and the data backs it up. According to the long-running Standish Group CHAOS research, only around 31% of software projects succeed on time, on budget, and with full scope, while roughly 19% fail outright and the remainder are \"challenged\" — late, over budget, or missing features. The picture gets worse with scale: small projects succeed at close to a 90% rate, while large projects succeed less than 10% of the time.",
   "The budget numbers are equally sobering. The median cost overrun on large IT projects sits at around 45% above the original estimate, and for very large projects — those over roughly $15 million — average overruns exceed 66%. A smaller but still meaningful share of projects become what researchers call \"black swans\" — around one in six IT projects overruns its budget by 200% on average, with the most extreme documented case reaching nearly 700%.",
   "What's genuinely useful in this research isn't the failure rate itself — it's the \"why.\" The most commonly cited causes of software project failure are unclear requirements, scope creep, inadequate planning, and communication breakdowns — not, in most cases, the technology itself. That finding matches almost exactly what we see across our own engagements: the projects that go sideways are rarely undone by a hard technical problem. They're undone by a requirement nobody pinned down at the start, or a change nobody flagged before it hit the codebase.",
   "It's also worth noting that agile delivery approaches consistently overrun less than traditional waterfall methods, across every project size studied — which is precisely why every Via Codos engagement is scoped and delivered in two-week sprints with a working demo at the end of each one, rather than a single, high-risk delivery date six months out. You don't have to accept the industry's failure rate as the price of building custom software. You just have to work with a partner whose process is actually built to avoid the specific mistakes that research keeps finding."]),
 dict(slug="hidden-cost-missed-call", title="The Hidden Cost of a Missed Call: What After-Hours Gaps Really Cost Service Businesses",
  cat="AI & Automation", date="July 2026", read="5 min read",
  excerpt="Every business that answers a phone has felt it: the call that comes in after hours, goes unanswered, and never comes back.",
  body=["Every business that answers a phone has felt it: the call that comes in after hours, goes unanswered, and never comes back. What's less obvious is how much that actually costs over the course of a year.",
   "Adoption of AI voice and chat agents has grown specifically because this problem is measurable and expensive. Customer service is now the single most AI-adopted business function, at 56% adoption, and the reason is straightforward economics: AI can resolve a routine customer interaction for well under a dollar, compared to several dollars for the same interaction handled by a person — a gap that compounds fast once you're talking about the after-hours and overflow volume most small and mid-sized businesses simply can't staff for.",
   "The businesses seeing the strongest results aren't the ones automating everything — they're the ones automating the specific, well-defined interactions that don't require judgment: booking a slot, capturing a lead's details, answering the same handful of questions that come up every single day. Businesses deploying AI agents for exactly this kind of work report measurable revenue growth in the 3-15% range, alongside a 10-20% lift in sales-related ROI, largely because leads that used to go cold overnight are now captured the moment they call.",
   "The gap between adoption and real value still comes down to the same thing across every AI use case we've studied: integration. An AI agent that answers calls but doesn't talk to your actual scheduling and CRM systems just creates a different kind of missed opportunity — a lead captured but never followed up on. That's the specific problem our AI Call Colleague platform was built to solve: not just picking up the phone, but making sure everything it captures lands exactly where your team already works."]),
 dict(slug="sri-lanka-tech-hub", title="Why Sri Lanka Is Emerging as a Top Tech Outsourcing Destination",
  cat="Outsourcing", date="June 2026", read="5 min read",
  excerpt="For a decade, IT outsourcing conversations defaulted to a small handful of countries. That default is shifting.",
  body=["For a decade, IT outsourcing conversations defaulted to a small handful of countries. That default is shifting, and Sri Lanka has quietly become one of the strongest arguments for looking beyond the usual list.",
   "The foundation is education. Sri Lanka produces a steady stream of STEM graduates every year from a university system with a strong mathematics and engineering tradition, and English is taught as a core academic subject from primary school onward — which shows up directly in how easily Sri Lankan engineering teams communicate with international clients, without the translation friction that slows down requirements gathering elsewhere.",
   "The second factor is cost structure, but not in the way people usually mean it. Cost savings in Sri Lanka come from a genuinely lower cost of living and operating expense, not from lower engineering standards. Businesses that partner with vetted Sri Lankan teams typically see cost reductions in the 40-70% range compared to onshore hiring in the US, UK, or Australia, while working with engineers trained to the same technical standards those markets expect.",
   "Finally, there is stability of relationship. Because the local tech workforce is still growing relative to global demand, turnover among strong engineers tends to be lower than in oversaturated markets — which matters enormously for outsourcing relationships, where continuity of institutional knowledge is often worth more than the code itself.",
   "None of this means every outsourcing engagement in Sri Lanka succeeds automatically. The differentiator is still the partner you choose — how rigorously they vet talent, how transparently they communicate, and how seriously they take security and IP protection. But the underlying talent pool and cost fundamentals make a strong case for putting Sri Lanka on your shortlist."]),
 dict(slug="ai-customer-service", title="The Future of AI in Customer Service: 24/7 Virtual Agents",
  cat="AI & Automation", date="May 2026", read="4 min read",
  excerpt="Customer service has a structural problem no amount of hiring fully solves: demand doesn't respect business hours.",
  body=["Customer service has a structural problem that no amount of hiring fully solves: demand for support doesn't respect business hours, and staffing around the clock is expensive for anyone below enterprise scale.",
   "Conversational AI agents are closing that gap in a way that finally feels production-ready rather than experimental. Modern natural-language systems can handle appointment booking, order status, lead qualification, and first-line support with a level of fluency that would have seemed implausible even three years ago — and they do it without hold times, without shift schedules, and without the burnout that comes with high call-volume roles.",
   "The businesses getting the most value from this shift are not the ones trying to automate everything. They are the ones being deliberate about where automation genuinely helps: repetitive, well-defined interactions get handled instantly by the AI, while anything requiring judgement, empathy at a difficult moment, or a decision outside the agent's defined boundaries gets escalated cleanly to a human. That escalation design, done well, is what separates a virtual agent customers trust from one they learn to avoid.",
   "The near-term future of this space is less about the AI getting smarter in the abstract, and more about integration — voice and chat agents that share full context with a business's CRM and scheduling systems, so a customer never has to repeat themselves to a human after starting with the AI. Businesses that get that integration right will see the compounding benefit: faster response times, lower staffing costs, and a customer experience that feels more attentive, not less."]),
 dict(slug="automotive-erp-signs", title="5 Signs Your Automotive Business Needs an ERP System",
  cat="ERP", date="May 2026", read="6 min read",
  excerpt="Most automotive businesses don't decide to get an ERP — they get pushed into it by an accumulation of daily frictions.",
  body=["Most automotive service and repair businesses don't decide to get an ERP system — they get pushed into it by an accumulation of small daily frictions that eventually become too expensive to ignore. Here are five signs that point is closer than it looks.",
   "First: your technicians regularly wait on parts they didn't know were out of stock. If job cards routinely stall because nobody had real-time visibility into inventory, you're paying for that delay in idle labour hours every single day.",
   "Second: customer history lives in someone's memory, not your system. If a returning customer's full service history depends on which staff member happens to be on shift, you have no reliable record — and no ability to spot patterns that predict future repairs or upsell opportunities.",
   "Third: your month-end reporting takes days instead of minutes. If closing the books means someone manually reconciling numbers from three different tools, that is a sign your systems aren't actually talking to each other.",
   "Fourth: you're planning to open a second location. Multi-location operations without a unified system almost always fragment into inconsistent pricing, duplicated inventory purchases, and inconsistent customer experience between branches.",
   "Fifth: your growth has outpaced your spreadsheets. Spreadsheets are a perfectly reasonable tool for a single-location business with a handful of staff. Past that point, they become a liability — error-prone, hard to audit, and impossible to scale.",
   "If two or more of these describe your business today, the cost of continuing to operate without an ERP system is very likely higher than the cost of implementing one."]),
 dict(slug="scaling-engineering-teams", title="Building Scalable Engineering Teams: From 1 to 50 Engineers",
  cat="Technology", date="April 2026", read="7 min read",
  excerpt="The practices that work at three engineers break down at fifteen — and again well before fifty.",
  body=["Scaling an engineering team is rarely a smooth, linear process. The practices that work when you have three engineers actively break down at fifteen, and what works at fifteen breaks down again well before fifty. Understanding where those breakpoints occur makes the transition far less painful.",
   "In the earliest stage, with one to five engineers, speed matters more than process. Documentation is thin, communication happens informally, and that's appropriate — formal process at this stage slows you down for no benefit. The main risk is technical debt accumulating invisibly, so it's worth designating even a lightweight code review habit early, before it feels necessary.",
   "Between five and fifteen engineers, informal communication starts to fail quietly. Decisions made in one conversation stop reaching everyone who needs them, and the team starts shipping inconsistent patterns because there's no shared architectural reference. This is the point to introduce structured sprint planning, a written (even if brief) architecture decision log, and clear ownership boundaries between subsystems.",
   "From fifteen to fifty, the challenge shifts from communication to integration risk. More engineers working in parallel means more chances for changes to collide, so CI/CD discipline, automated testing coverage, and a genuine QA function stop being optional and become the thing that determines whether velocity keeps increasing or starts declining under its own weight.",
   "Outsourcing and staff augmentation can meaningfully de-risk this journey, particularly through the five-to-fifteen transition, by giving you access to engineers who have already been through scaling transitions elsewhere and can help you avoid mistakes rather than discover them the hard way. The key is choosing a partner who augments your existing culture and standards rather than working around them."]),
 dict(slug="real-estate-digital-transformation", title="Digital Transformation Trends in Real Estate",
  cat="Industry Insights", date="April 2026", read="5 min read",
  excerpt="Real estate has historically been slow to digitise. That is changing quickly — and the fastest movers are pulling ahead.",
  body=["Real estate has historically been one of the slower industries to digitise — relationships and local market knowledge mattered more than software. That is changing quickly, and the agencies moving fastest on technology are pulling ahead on both efficiency and customer experience.",
   "The clearest trend is consolidation of listing and lead data. Agencies that used to juggle multiple portals, spreadsheets, and a CRM that nobody updated consistently are moving toward unified platforms where a lead, a listing, and a transaction are all connected records rather than disconnected entries someone has to reconcile manually.",
   "The second trend is speed of response becoming a genuine competitive differentiator. Buyers and renters increasingly expect a reply within minutes, not the next business day, and agencies with automated lead-routing and instant acknowledgment systems are converting inquiries that slower competitors simply lose.",
   "Digital transaction management is the third major shift — from document signing to milestone tracking — reducing the administrative overhead that used to consume agent time between an accepted offer and a closed deal.",
   "None of these shifts require an agency to become a technology company. They require choosing the right systems and, in many cases, the right technology partner to implement them without disrupting the relationships that still ultimately close deals."]),
 dict(slug="500-projects-milestone", title="Via Codos Celebrates 500+ Projects Milestone",
  cat="News", date="March 2026", read="3 min read",
  excerpt="Via Codos has now delivered more than 500 completed projects for clients across six continents.",
  body=["Via Codos has now delivered more than 500 completed projects for clients across the United States, United Kingdom, Australia, Dubai, South Africa, and beyond — a milestone that reflects the trust our clients have placed in us since our founding.",
   "Since our inception, our focus has stayed consistent: connect global businesses with genuinely vetted Sri Lankan engineering talent, and deliver software and outsourcing engagements with the transparency and accountability that outsourcing relationships too often lack. Reaching this milestone is a testament to the engineers, designers, and project leads who have made that promise real on every engagement.",
   "This milestone also reflects the range of what our teams now deliver — from the BeltKit ERP platform now running in over one hundred automotive service centres, to Qalam MMS supporting more than two hundred community institutions, to AI Call Colleague handling calls around the clock for businesses that once struggled with after-hours coverage.",
   "We're grateful to every client who trusted us with their technology, and to the growing team that continues to make that trust worth having. Five hundred projects is a milestone worth marking — and, with the pace of new engagements underway, not one we expect to sit on for long."]),
]

TEAM = [
 dict(name="Aadil Rizam", role="CEO & Founder — Strategic Leadership", img="team_1.jpg",
  bio="Sets the company's direction and oversees client partnerships, with a focus on making sure every engagement delivers measurable business value, not just delivered code."),
 dict(name="Aabid Rizam", role="Head of Engineering — Full Stack Development", img="team_2.jpg",
  bio="Leads engineering standards and architecture review across every project, ensuring what we ship is maintainable long after launch, not just functional on delivery day."),
 dict(name="Hiruna Weerakoon", role="AI & Automation Lead — Machine Learning", img="team_3.jpg",
  bio="Directs the design and deployment of AI systems including the AI Call Colleague platform, with particular focus on safe escalation design and real-world reliability."),
 dict(name="Sachintha Fernando", role="Head of Outsourcing — Talent Acquisition", img="team_4.jpg",
  bio="Owns the vetting pipeline that keeps our engineer bench at the standard clients expect — technical assessment, live coding, and culture-fit review for every placement."),
]

JOBS = [
 dict(title="Senior Software Engineer", meta=["Full-time","Remote","5+ years experience","Java · Spring · React · AWS"],
  resp=["Lead architecture decisions for client-facing modules","Mentor mid-level engineers within your pod","Own code quality and review standards for your workstream"]),
 dict(title="Full Stack Developer", meta=["Full-time","Remote","3+ years experience","Python · Django · Vue.js"],
  resp=["Build and maintain full-stack features end to end","Collaborate directly with client stakeholders during sprint demos","Write and maintain automated test coverage for your code"]),
 dict(title="DevOps Engineer", meta=["Full-time","Remote","3+ years experience","AWS · Docker · Kubernetes · CI/CD"],
  resp=["Design and maintain CI/CD pipelines across client projects","Manage cloud infrastructure and cost optimisation","Implement monitoring and incident response processes"]),
 dict(title="AI/ML Engineer", meta=["Full-time","Remote","2+ years experience","TensorFlow · PyTorch · NLP · LLMs"],
  resp=["Build and fine-tune conversational AI and automation models","Design escalation and safety guardrails for production AI systems","Collaborate with the AI & Automation Lead on new product features"]),
 dict(title="Mobile Developer", meta=["Full-time","Remote","2+ years experience","React Native · Flutter · iOS · Android"],
  resp=["Build cross-platform and native mobile features","Manage App Store and Google Play submission cycles","Monitor post-launch crash reporting and performance"]),
 dict(title="QA Automation Engineer", meta=["Full-time","Remote","2+ years experience","Selenium · JUnit · TestRail"],
  resp=["Build and maintain automated regression test suites","Write test plans directly from client requirements","Integrate automated testing into CI/CD pipelines"]),
]
